version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: rachaelwilliams-redirect
    command: sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "${EXTERNAL_PORT}:8123"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/redirect.conf:ro
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    external: true
