version: '3.8'

services:
  nginx:
    build: .
    container_name: rachaelwilliams-redirect
    ports:
      - "${EXTERNAL_PORT:-80}:8123"
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    external: true
