version: '3.8'

services:
  nginx:
    build: .
    container_name: rachaelwilliams-redirect
    restart: unless-stopped
    ports:
      - ":8123"
    networks:
      - app_net

networks:
  app_net:
    external: true
